version: '3.7'
networks:
  dbnet:
    external: true
services:
  mysql:
    container_name: 'mysql8'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    build: './mysql'
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - dbnet
  postgres:
    container_name: 'pgsql13'
    environment:
      POSTGRES_PASSWORD: secret
    build: './postgres'
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - dbnet
