version: '3.7'
services:
  mysql:
    image: '${IMAGE_CONTAINER_PREFIX}_mysql8'
    container_name: '${IMAGE_CONTAINER_PREFIX}_mysql8'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    build: './mysql'
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - dbnet
  mariadb:
    image: '${IMAGE_CONTAINER_PREFIX}_mariadb10.7'
    container_name: '${IMAGE_CONTAINER_PREFIX}_mariadb10.7'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    build: './mariadb'
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
    networks:
      - dbnet
  #postgres:
    #image: '${IMAGE_CONTAINER_PREFIX}_pgsql13'
    #container_name: 'container-pgsql13'
    #environment:
      #POSTGRES_PASSWORD: secret
    #build: './postgres'
    #restart: unless-stopped
    #ports:
      #- 5432:5432
    #volumes:
      #- ./postgres/data:/var/lib/postgresql/data
    #networks:
      #- dbnet
  #redis:
    #image: redis:6.2
    #container_name: 'redis6'
    #expose:
      #- 6379
    #volumes:
      #- ./redis/data:/data
    #networks:
      #- dbnet

networks:
  dbnet:
    driver: bridge